### ISSUE TITLE
Event registrations broken

### ISSUE THREAD

**Issue by sheadawson** [titledk/silverstripe-calendar#12]
Tried to register to this event on the demo site http://calendar.demo.title.dk/calendar/detail/294, got redirected here

![screen shot 2015-11-04 at 4 13 02 pm](https://cloud.githubusercontent.com/assets/1166136/10928606/03bdc834-830f-11e5-90ca-6bf74a2d375b.png)

How complete is the event registration stuff now? I've got a couple of projects possibly coming up that will either need to use this calendar module OR Uncle Cheese's + event management addon for registerable/payable events. Hard decision, although I can see that you guys have put a really good effort into this module and are a bit more current/active. Either option it seems there would be a bit of work to do

**Comment by anselmdk** [comment]
Thanks for letting me know.
I just fixed that in https://github.com/titledk/silverstripe-calendar/commit/1c92a95b2a49e2f0f6d96e2bdff153d9406f5208 and updated the demo site.

It seems calling the controller directly is no more valid in `3.2`. Which reminds me it would be beneficial with some Behat tests :)

The event registration implementation is pretty simple so far - it's basically taken from a client project and merged back here, so it would need to be amended for a real-life scenario, and preferably made configurable.
For now you can find the registrations in the backend here:
http://calendar.demo.title.dk/admin/calendar/ComingEventsForm/field/Events/item/294/edit
(info@title.dk / password)

![screenshot 2015-11-04 09 10 05](https://cloud.githubusercontent.com/assets/1316533/10932803/11dcdce2-82d4-11e5-8654-9b97d8ec11d3.png)

I've been thinking of moving stuff like registrations, the full calendar, private calendars etc. out into their own modules, to keep a lean an maintainable core, so if you decide to go this way, maybe that's what we could do.
I've myself thought of revising registrations, as I'm thinking to build a simple booking system for our home yoga center based on this module, not sure exactly when it'll happen though.

I'm happy to chat about it on Gitter: https://gitter.im/titledk/silverstripe-calendar
