### ISSUE TITLE
Categories & category filtering don't seem implemented on the front-end(?)

### ISSUE THREAD

**Issue by micschk** [titledk/silverstripe-calendar#14]
I haven't been able to find any logic to filter by category in php, nor in the front-end/templates. 

Thought I'd report, as it's not clear from the readme that this is not implemented.

**Comment by anselmdk** [comment]
True. It should only be a few lines in your code though. Something in the lines of https://github.com/titledk/silverstripe-calendar/blob/248253f8113f9063bf4349a60cd7464d4891b29d/code/pagetypes/CalendarPage.php#L235
Would probably a good idea to add it to the README.

**Comment by anselmdk** [comment]
I think that should solve it? I'll close this issue.

**Comment by 11nf0s3c** [comment]
I am looking to display the categories on the front end/templates and then filter the events by category as well? Possible?
