### ISSUE TITLE
CalendarConfig

### ISSUE THREAD

**Issue by HilkiahMakemo** [titledk/silverstripe-calendar#27]
Is this still active or is it not? If it is, where exactly is CalendarConfig class for initial installation?

**Comment by anselmdk** [comment]
Yes it is.
Here is an example of how he calendar can be initialized:
https://github.com/titledk/silverstripe-calendar-demo/blob/master/public/mysite/_config.php#L16

**Comment by HilkiahMakemo** [comment]
I get this error:
Fatal error: Class 'CalendarConfig' not found in /var/www/html/mysite/_config.php on line 31

**Comment by anselmdk** [comment]
It's here, part of the module:
https://github.com/titledk/silverstripe-calendar/blob/master/code/core/CalendarConfig.php

**Comment by HilkiahMakemo** [comment]
Hey that was really fast response so thanks!
However, Calendar code directory contains an Event class and an Object class that are not available in the package I installed which is currently in composer (dev-master). Should I be getting it from another source, say Github or Packagist, etc.?
I’m I even tried changing Event to CalendarEvent, noticed the add_extensions method is not a in CalendarEvent.
Any reason for this o­r where should I get the complete package?

**Comment by anselmdk** [comment]
That sounds very strange.
I actually have merged quite a few pull requests to master lately which I haven' tried locally.
You could try with the version from here: https://github.com/titledk/silverstripe-calendar-demo/blob/master/public/composer.json

That is `"titledk/silverstripe-calendar": "1.1.x-dev"`.

That should for sure work as it's live on http://calendar.demo.title.dk

You could also try installing the calendar demo locally (see https://github.com/titledk/silverstripe-calendar-demo#installation). If that doesn't work it's likely an issue with your setup.

**Comment by anselmdk** [comment]
Here is the event class by the way:
https://github.com/titledk/silverstripe-calendar/blob/master/code/events/Event.php

**Comment by anselmdk** [comment]
You are aware of that you need SilverStripe framework for the module to work? I see it's not required in the `composer.json` file... I should probably add that it.

**Comment by HilkiahMakemo** [comment]
Ok, yes I have silverstripe framework and I ended up downloading the zip from github and uncompressed it and vuala it works. I tried updating composer.json to the version 1.1.x-dev from dev-master but didn’t do the trick. So seems the composer version was the issue, but I’m good now thanks a lot!

**Comment by anselmdk** [comment]
Great to hear.
I've renamed the issue to "Issues with installing from composer" for later review.
