### ISSUE TITLE
Installation - not knowing how..

### ISSUE THREAD

**Issue by MondID** [titledk/silverstripe-calendar#28]
Hi all -

I am fairly new to Silverstripe and much, much newer to this add-on.

Could you please give me a more detailed heads-up on how to install this add-on; I've downloaded the .zip from GIT -- but what's next?

I've got a 'shadow' installation of my site running locally through WAMP, and am using Composer normally. 

Thanks heaps for your assistance [apologies for this very basic 'you-should-know-this-by-now' kind of question...

Raymond

**Comment by anselmdk** [comment]
Hi,
I think this should help:
https://docs.silverstripe.org/en/3.2/developer_guides/extending/modules/#installation

The gist is just to put the directory into your web root and run `/dev/build?flush` (make sure it's renamed to calendar). Overall you should consider using composer to install this module though.

For the future I'd prefer if you use the [Gitter Channel](https://gitter.im/titledk/silverstripe-calendar) for such kind of issues. I'm happy to try and help.

**Comment by terryapodaca** [comment]
Don't forget to put

CalendarConfig::init()

with your proper config array in your _config file.

On Thu, Feb 4, 2016 at 12:29 AM, Anselm Christophersen <
notifications@github.com> wrote:

> Hi,
> I think this should help:
>
> https://docs.silverstripe.org/en/3.2/developer_guides/extending/modules/#installation
>
> The gist is just to put the directory into your web root and run
> /dev/build?flush (make sure it's renamed to calendar). Overall you should
> consider using composer to install this module though.
>
> For the future I'd prefer if you use the Gitter Channel
> <https://gitter.im/titledk/silverstripe-calendar> for such kind of
> issues. I'm happy to try and help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titledk/silverstripe-calendar/issues/28#issuecomment-179669042>
> .
>



-- 
-Terry

**Comment by anselmdk** [comment]
true... Thanks Terry!

**Comment by MondID** [comment]
Thanks heaps Anselm and Terry. 

I think I may need someone's help installing this. Happy to pay. Isn't working for me...

Raymond

**Comment by terryapodaca** [comment]
I have installed this several times. I believe over the last several months, though, they have updated some of the code. I would be willing to help you, but first I want to know what version of SS you are using and what version of this module are you trying to install?

**Comment by MondID** [comment]
Hi Terry -

Would be great to get your support. Running SS 3.2 currently. I'll send you my contact details via PM now.
