### ISSUE TITLE
Update to the actual fullcalendar

### ISSUE THREAD

**Issue by leclerc** [titledk/silverstripe-calendar#35]
The actual Fullcalendar is version 2.9.1 and has many useful functions, JS is unfortunately not my niche and just couldn't make it work, it would be really nice to have the new functionality in this awesome module.

**Comment by anselmdk** [comment]
@leclerc there has been some work done on this here:
https://github.com/denkfabrik-neueMedien/silverstripe-calendar/tree/fullcalendar-update

Expect it in master soon!

**Comment by leclerc** [comment]
@anselmdk 
Great, currently I am working a pretty complex project and one part is heavily based on Your module, I am really grateful for it!

**Comment by anselmdk** [comment]
Nice to hear it's appreciated!
