### ISSUE TITLE
Is this compatible with SilverStripe version 4?

### ISSUE THREAD

**Issue by gingin77** [titledk/silverstripe-calendar#52]

**Comment by anselmdk** [comment]
There is an open PR (work in progress) on it: https://github.com/titledk/silverstripe-calendar/pull/48

**Comment by terryapodaca** [comment]
@gingin77 I know this issue is closed, and Anselm explained why, but did you ever find a suitable replacement option since this module isn't quite ready for SS4 yet?

**Comment by gingin77** [comment]
Rather than managing calendar events within our web app, we use Google Calendar. I have a service account that holds the necessary api credentials on the  backend and obtains the data I need. Then I pass the data from the backend to some frontend JS functions and render a calendar view using the full calendar JS library.

**Comment by terryapodaca** [comment]
Thanks for the update. That sounds a bit complicated. Maybe I'll look at developing something and using that fullcalendar js library for the front end like this module did...but just keep it simple. Thanks again!

**Comment by gingin77** [comment]
@terryapodaca, another person reached out and asked me about this, so I wrote up a post in Medium outlining the process I took - [Displaying Google Calendar Events in a SilverStripe 4 app with FullCalendar ](https://medium.com/@engineniches/integrating-google-calendar-with-fullcalendar-js-into-a-silverstripe-4-app-88667fafec7a)
